### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by navFooh**

### CODE REVIEW

**Review by Schwartz10 — CHANGES_REQUESTED** [review]
Just need to fix some imports @navFooh then this should pass and lgtm! Exciting...

**Comment by navFooh** [comment]
> Just need to fix some imports @navFooh then this should pass and lgtm! Exciting...

Ok, just did one more tiiiiny update to get rid of the old `Button`, `Num` and `Label` 🙄😅

**Review by Schwartz10 — COMMENTED** [review]
@navFooh i dont have a great way to test the different states of the reveal mnemonic component changes (i get errors with zondax lib when i npm link...). Besides that, this PR looks good to me. Feels good to delete so much code. I'm happy to merge and publish if you feel good about the changes to the reveal mnemonic flow components

**Comment by navFooh** [comment]
> @navFooh i dont have a great way to test the different states of the reveal mnemonic component changes (i get errors with zondax lib when i npm link...). Besides that, this PR looks good to me. Feels good to delete so much code. I'm happy to merge and publish if you feel good about the changes to the reveal mnemonic flow components

Yeah I know, it's kind of hard to QA that properly now. I thought the `CreateSeed` story worked before, but now it does not. That's why I created the `RevealMnemonic` story to at least be able to see the changes in the updated component. The changes I did are purely in layout and styling which can be verified there. Functionally it did not change, so I am confident this won't cause any issues.

**Pull request merged**
